name: Create Kubernetes Cluster
on:
  push:
    branches:
      - develop

jobs:
  create-cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install k3d
      run: |
        wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

    - name: Create k3d cluster
      run: |
        k3d cluster create mycluster

    - name: Set kubeconfig
      run: |
        k3d kubeconfig merge mycluster --kubeconfig-switch-context

    - name: Verify cluster
      run: |
        kubectl cluster-info

# name: KBOT-CICD

# on: 
#   push:
#     branches:
#       develop

# jobs:
#   ci:
#     name: CI
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0

#       - name: Run tests
#         run: make test

#       - name: Docker login
#         uses: docker/login-action@v2
#         with:
#           registry: ghcr.io
#           username: ${{ secrets.GHCR_USERNAME }}
#           password: ${{ secrets.GHCR_TOKEN }}

#       - name: Build & Push
#         env:
#           APP: "kbot"
#           REGISTRY: ghcr.io/${{ secrets.GHCR_USERNAME }}
#         run:
#           make image push

  # cd:
  #   name: CD
  #   needs: ci
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       fetch-depth: 0
  #   - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

  #   - uses: mikefarah/yq@master
  #     with:
  #       cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml
        
  #   - run: |
  #       git config user.name github-actions
  #       git config user.email github-actions@hithub.com
  #       git commit -am "Update version $VERSION"
  #       git push
